apiVersion: v1
baseDomain: bca.gov.vn
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: hub
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.171.132.0/24
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  baremetal:
    apiVIP: "10.171.132.41"
    ingressVIP: "10.171.132.42"
pullSecret: '{"auths":{"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfNmQ3ZGI1YWExODYwNDlmOGE5OTE1YjQwNmFkMDBmNmM6RFgwQlZaVU84SVA0WlRIMFdTRFdNUjBOWUo0QzhUUzJLVzlFQVM5NTZKV0ZVUUo2OUpCNDJDT0pFQ044T1dERg==","email":"nguyenduchuy@vnpt.vn"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLWU2YjdmMjgxLWQ1NDAtNDk2MC05MDY4LTcxMTdiMGJlODM2NjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTFNbVV5WkRoaVlXSXpPV0kwTkRreVltUmpZMkUxWkRBd01Ua3lNMlZpTkNKOS5ON2FGQmo3OHhNeXA1Q0lQZ0lrV1FleTBnSC0tWlpiRXVsdWVIWGhEQjVMZFNlS3J3VTlnOS1JbHZyZG5hbXVhTGV2VGNUZncyZ0M0ZlpMRXlsRGQxT01DSVNCUm52Z1RxN2JxRXJIOXdqSkF3WnR6blAxRFZ6engyUloxQjV0dW5YVXhucmt5cEJieF9oVnl6YjlJdXNBLVFIX1pCNXpZWEJaMGhrOGhJOEM5WXBCeGdoekhZZjlzRDhNR2hmSGptTDAxRC1WZFd3MlVYN2JVaFdVd0R2c2ZvZ3RCb2hiX1NKVGVJTjBOQk1seGg5ZEpSV3htaDQwc3FKUVVpZUhqVE1oMjhUdDhweVBKNV9XNS1TUnEzRHlGQVgtcVFocVd2YkdyOGhxTlFMTEV1SDQxRUVteDVUZktSOHMxWnN0Q1VmQ0kwdkM0R1lWLVdoOTlWazdSemFLSE5xdFRocFNldWtSa0g3YmVSbGZ6TnFfTGlBNko1OUxmVmVsUFpPcTZiS0N0R2JEa1A5VEl0TF9TeWFNc1YyeDlLSWZxYzdST2VlcXpTRWJVTUljcUpqcTg5eWUyZFY1ZU1EV3lpRVhTT0ExMElUME1vSXZtTERVaHlJOVNsTGVfVE5ILUpHU3ZkdXFZU2RtTm5aYjZwSGhHR3Mzd3pBc01tQndnT01Nc0hVNWJDX0hST3hDdVJpQXNseTlBRFBKQ3NzQlBURWQxOE02cE5faVdtRlZTNWx4NTVHRW5jdWxBU1lpUE4xRm1hbDR5MnNKQVZOVkIyX2xXcm5pSEZXVVM0cXdNRE1NX3FTRTdCMzVYaGFMbXN6b0NIMFZHZGdNVjR3aVl4dFc1Vl93a1ppclZwSFVydVJuZTE0YjBDbjU3eEtoQ19zYms0em5zeTZOYUxxYw==","email":"nguyenduchuy@vnpt.vn"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLWU2YjdmMjgxLWQ1NDAtNDk2MC05MDY4LTcxMTdiMGJlODM2NjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTFNbVV5WkRoaVlXSXpPV0kwTkRreVltUmpZMkUxWkRBd01Ua3lNMlZpTkNKOS5ON2FGQmo3OHhNeXA1Q0lQZ0lrV1FleTBnSC0tWlpiRXVsdWVIWGhEQjVMZFNlS3J3VTlnOS1JbHZyZG5hbXVhTGV2VGNUZncyZ0M0ZlpMRXlsRGQxT01DSVNCUm52Z1RxN2JxRXJIOXdqSkF3WnR6blAxRFZ6engyUloxQjV0dW5YVXhucmt5cEJieF9oVnl6YjlJdXNBLVFIX1pCNXpZWEJaMGhrOGhJOEM5WXBCeGdoekhZZjlzRDhNR2hmSGptTDAxRC1WZFd3MlVYN2JVaFdVd0R2c2ZvZ3RCb2hiX1NKVGVJTjBOQk1seGg5ZEpSV3htaDQwc3FKUVVpZUhqVE1oMjhUdDhweVBKNV9XNS1TUnEzRHlGQVgtcVFocVd2YkdyOGhxTlFMTEV1SDQxRUVteDVUZktSOHMxWnN0Q1VmQ0kwdkM0R1lWLVdoOTlWazdSemFLSE5xdFRocFNldWtSa0g3YmVSbGZ6TnFfTGlBNko1OUxmVmVsUFpPcTZiS0N0R2JEa1A5VEl0TF9TeWFNc1YyeDlLSWZxYzdST2VlcXpTRWJVTUljcUpqcTg5eWUyZFY1ZU1EV3lpRVhTT0ExMElUME1vSXZtTERVaHlJOVNsTGVfVE5ILUpHU3ZkdXFZU2RtTm5aYjZwSGhHR3Mzd3pBc01tQndnT01Nc0hVNWJDX0hST3hDdVJpQXNseTlBRFBKQ3NzQlBURWQxOE02cE5faVdtRlZTNWx4NTVHRW5jdWxBU1lpUE4xRm1hbDR5MnNKQVZOVkIyX2xXcm5pSEZXVVM0cXdNRE1NX3FTRTdCMzVYaGFMbXN6b0NIMFZHZGdNVjR3aVl4dFc1Vl93a1ppclZwSFVydVJuZTE0YjBDbjU3eEtoQ19zYms0em5zeTZOYUxxYw==","email":"nguyenduchuy@vnpt.vn"},"registry.hub.bca.gov.vn:8443":{"auth":"aHV5bmQ6Vm5wdEAxMjMhQCM="}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj3GM0JytAzH4k9IyQUQEAW8ZBpCNlGjKPLtyPiq4/sd2kz32EUinSMRUysa7Wx06Xm8dppvTFqyAt8oFk5f4ssai1CIKgqpzGhFSR21rtYckEnvfB1WVoT+qk6kHY0Lni280f4/vHGO1qRVP6bLo00jLR6zWqIJ9zViaGr8m3PCxhWzr7PBeZA8hH/VLucQ7REMw2F2m5IZEvedq8IZA6bCeh5h0oO0LpUSUhhy2xIkjtxpLbNURRR+9qRa1tI2QqgLCmk3Tj7vraVtz0nRHpdSGqSl4DzdTtw7iLOrtF9RgrvaJUBNb709hFBaePlmogqmItv6KerfZJmYww+ltKViUKhaJ3Fs+oT5h7/pXXuIwQF7RSkHGKs8LA+GFFYzy9wYfc8kepgVAVeIlF7te6SJYsDp9tWF18GzlsL3365gU5NaB94V7oOfoHYVibzoo+O92MPLo8zx3bC6kXR1HPj8b4zju0hE3uDVzf9+WVdnaSekvaqSQT1n0DnRglqVE= root@services.novalocal'
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
MIID6zCCAtOgAwIBAgIUF182XG/U8xdRkz176guPLMUTQHUwDQYJKoZIhvcNAQEL
BQAwcTELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xIDAeBgNVBAMMF3Jl
Z2lzdHJ5Lmh1Yi5iY2EuZ292LnZuMB4XDTI1MDYyMzEwNDEzNloXDTI4MDQxMjEw
NDEzNlowcTELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcg
WW9yazENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xIDAeBgNVBAMM
F3JlZ2lzdHJ5Lmh1Yi5iY2EuZ292LnZuMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEAxpr4bPFx/HNgNKuja9m4ZqPizsCUp+1wR5IvYeoTktFmRa8cvNW7
wY7Z8FIYi81CBnsyx3KGvuFSPsDjOEJ+8Tyh/RI1JOFOxv1EvG+VGM93hLULc+9d
t1VRFkxzuuOlUYlWo5NnzUbZQOo/SyGBRv/Vu2jFTpKZG6VQmTd0icf39FTLiR/y
3D1kDpdZgfKtiTBtQ8Dq9KhKqQ7IRMTQE4DE3lja9DubmuywIfipnBvfLRP6O4FV
gCCfxMbwmBqmNGWz/ASh5DX3Kix5X1hn0gknB6548mAv2I+b94X/2eudbBA8TY/f
0/fq6GxdKs3ljnfpMlH6l+BymD48/NM7DQIDAQABo3sweTALBgNVHQ8EBAMCAuQw
EwYDVR0lBAwwCgYIKwYBBQUHAwEwIgYDVR0RBBswGYIXcmVnaXN0cnkuaHViLmJj
YS5nb3Yudm4wEgYDVR0TAQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQUEvlXeh1W4vTo
AT0S4BT+7Gqwf0QwDQYJKoZIhvcNAQELBQADggEBAHhbDVPpUBKDuH81s7cpiQwc
BfF+iNyYq0JD3IbupGaiFjj+dCNIvYUXAAHv9l+HBxmQVnWg4+pzOJbikjHlFVxh
qOQ/sb3PT42f6dM3wY5kLattva08sbNCD7EKiUWoJTkaQ7Jj1cJvBgXyBE2tUBf8
V8BFpYEQpywMa29e/DsOrbzYECvSBs4gSrtSiapcMQ8xWogEMO9m9Ff63T8SZqIU
94T4KahQP+WBBrAIknJBixPlzItTrqHnqd70l0ZMszi4uC3jmh7DlfG4qOevP6jT
AvL62BS+Jtv5J4Lh9dlyLqmP+KAOcgENK/ttYNISpTu4sMefVzgMgIwduzhQnDY=
-----END CERTIFICATE-----
imageDigestSources:
- mirrors:
  - registry.hub.bca.gov.vn:8443/openshift/release
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
- mirrors:
  - registry.hub.bca.gov.vn:8443/openshift/release-images
  source: quay.io/openshift-release-dev/ocp-release
