hosts:
- hostname: compute01.hub.bca.gov.vn
  interfaces:
   - macAddress: fa:16:3e:b2:9c:08
     name: eth0
  networkConfig:
   interfaces:
     - name: eth0
       type: ethernet
       state: up
       mac-address: fa:16:3e:b2:9c:08
       ipv4:
         enabled: true
         address:
           - ip: 10.171.132.45
             prefix-length: 24
         dhcp: false
   dns-resolver:
     config:
       server:
       - 10.171.132.40
   routes:
     config:
     - destination: 0.0.0.0/0
       next-hop-address: 10.171.132.1
       next-hop-interface: eth0
       table-id: 254
  sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj3GM0JytAzH4k9IyQUQEAW8ZBpCNlGjKPLtyPiq4/sd2kz32EUinSMRUysa7Wx06Xm8dppvTFqyAt8oFk5f4ssai1CIKgqpzGhFSR21rtYckEnvfB1WVoT+qk6kHY0Lni280f4/vHGO1qRVP6bLo00jLR6zWqIJ9zViaGr8m3PCxhWzr7PBeZA8hH/VLucQ7REMw2F2m5IZEvedq8IZA6bCeh5h0oO0LpUSUhhy2xIkjtxpLbNURRR+9qRa1tI2QqgLCmk3Tj7vraVtz0nRHpdSGqSl4DzdTtw7iLOrtF9RgrvaJUBNb709hFBaePlmogqmItv6KerfZJmYww+ltKViUKhaJ3Fs+oT5h7/pXXuIwQF7RSkHGKs8LA+GFFYzy9wYfc8kepgVAVeIlF7te6SJYsDp9tWF18GzlsL3365gU5NaB94V7oOfoHYVibzoo+O92MPLo8zx3bC6kXR1HPj8b4zju0hE3uDVzf9+WVdnaSekvaqSQT1n0DnRglqVE= root@services.novalocal'
- hostname: compute02.hub.bca.gov.vn
  interfaces:
   - macAddress: fa:16:3e:d8:b4:73
     name: eth0
  networkConfig:
   interfaces:
     - name: eth0
       type: ethernet
       state: up
       mac-address: fa:16:3e:d8:b4:73
       ipv4:
         enabled: true
         address:
           - ip: 10.171.132.46
             prefix-length: 24
         dhcp: false
   dns-resolver:
     config:
       server:
       - 10.171.132.40
   routes:
     config:
     - destination: 0.0.0.0/0
       next-hop-address: 10.171.132.1
       next-hop-interface: eth0
       table-id: 254
  sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj3GM0JytAzH4k9IyQUQEAW8ZBpCNlGjKPLtyPiq4/sd2kz32EUinSMRUysa7Wx06Xm8dppvTFqyAt8oFk5f4ssai1CIKgqpzGhFSR21rtYckEnvfB1WVoT+qk6kHY0Lni280f4/vHGO1qRVP6bLo00jLR6zWqIJ9zViaGr8m3PCxhWzr7PBeZA8hH/VLucQ7REMw2F2m5IZEvedq8IZA6bCeh5h0oO0LpUSUhhy2xIkjtxpLbNURRR+9qRa1tI2QqgLCmk3Tj7vraVtz0nRHpdSGqSl4DzdTtw7iLOrtF9RgrvaJUBNb709hFBaePlmogqmItv6KerfZJmYww+ltKViUKhaJ3Fs+oT5h7/pXXuIwQF7RSkHGKs8LA+GFFYzy9wYfc8kepgVAVeIlF7te6SJYsDp9tWF18GzlsL3365gU5NaB94V7oOfoHYVibzoo+O92MPLo8zx3bC6kXR1HPj8b4zju0hE3uDVzf9+WVdnaSekvaqSQT1n0DnRglqVE= root@services.novalocal'
- hostname: compute03.hub.bca.gov.vn
  interfaces:
   - macAddress: fa:16:3e:79:d0:52
     name: eth0
  networkConfig:
   interfaces:
     - name: eth0
       type: ethernet
       state: up
       mac-address: fa:16:3e:79:d0:52
       ipv4:
         enabled: true
         address:
           - ip: 10.171.132.47
             prefix-length: 24
         dhcp: false
   dns-resolver:
     config:
       server:
       - 10.171.132.40
   routes:
     config:
     - destination: 0.0.0.0/0
       next-hop-address: 10.171.132.1
       next-hop-interface: eth0
       table-id: 254
  sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj3GM0JytAzH4k9IyQUQEAW8ZBpCNlGjKPLtyPiq4/sd2kz32EUinSMRUysa7Wx06Xm8dppvTFqyAt8oFk5f4ssai1CIKgqpzGhFSR21rtYckEnvfB1WVoT+qk6kHY0Lni280f4/vHGO1qRVP6bLo00jLR6zWqIJ9zViaGr8m3PCxhWzr7PBeZA8hH/VLucQ7REMw2F2m5IZEvedq8IZA6bCeh5h0oO0LpUSUhhy2xIkjtxpLbNURRR+9qRa1tI2QqgLCmk3Tj7vraVtz0nRHpdSGqSl4DzdTtw7iLOrtF9RgrvaJUBNb709hFBaePlmogqmItv6KerfZJmYww+ltKViUKhaJ3Fs+oT5h7/pXXuIwQF7RSkHGKs8LA+GFFYzy9wYfc8kepgVAVeIlF7te6SJYsDp9tWF18GzlsL3365gU5NaB94V7oOfoHYVibzoo+O92MPLo8zx3bC6kXR1HPj8b4zju0hE3uDVzf9+WVdnaSekvaqSQT1n0DnRglqVE= root@services.novalocal'
- hostname: compute04.hub.bca.gov.vn
  interfaces:
   - macAddress: fa:16:3e:aa:95:cb
     name: eth0
  networkConfig:
   interfaces:
     - name: eth0
       type: ethernet
       state: up
       mac-address: fa:16:3e:aa:95:cb
       ipv4:
         enabled: true
         address:
           - ip: 10.171.132.48
             prefix-length: 24
         dhcp: false
   dns-resolver:
     config:
       server:
       - 10.171.132.40
   routes:
     config:
     - destination: 0.0.0.0/0
       next-hop-address: 10.171.132.1
       next-hop-interface: eth0
       table-id: 254
  sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj3GM0JytAzH4k9IyQUQEAW8ZBpCNlGjKPLtyPiq4/sd2kz32EUinSMRUysa7Wx06Xm8dppvTFqyAt8oFk5f4ssai1CIKgqpzGhFSR21rtYckEnvfB1WVoT+qk6kHY0Lni280f4/vHGO1qRVP6bLo00jLR6zWqIJ9zViaGr8m3PCxhWzr7PBeZA8hH/VLucQ7REMw2F2m5IZEvedq8IZA6bCeh5h0oO0LpUSUhhy2xIkjtxpLbNURRR+9qRa1tI2QqgLCmk3Tj7vraVtz0nRHpdSGqSl4DzdTtw7iLOrtF9RgrvaJUBNb709hFBaePlmogqmItv6KerfZJmYww+ltKViUKhaJ3Fs+oT5h7/pXXuIwQF7RSkHGKs8LA+GFFYzy9wYfc8kepgVAVeIlF7te6SJYsDp9tWF18GzlsL3365gU5NaB94V7oOfoHYVibzoo+O92MPLo8zx3bC6kXR1HPj8b4zju0hE3uDVzf9+WVdnaSekvaqSQT1n0DnRglqVE= root@services.novalocal'
- hostname: compute05.hub.bca.gov.vn
  interfaces:
   - macAddress: fa:16:3e:04:de:b4
     name: eth0
  networkConfig:
   interfaces:
     - name: eth0
       type: ethernet
       state: up
       mac-address: fa:16:3e:04:de:b4
       ipv4:
         enabled: true
         address:
           - ip: 10.171.132.49
             prefix-length: 24
         dhcp: false
   dns-resolver:
     config:
       server:
       - 10.171.132.40
  routes:
    config:
    - destination: 0.0.0.0/0
      next-hop-address: 10.171.132.1
      next-hop-interface: eth0
      table-id: 254
  sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj3GM0JytAzH4k9IyQUQEAW8ZBpCNlGjKPLtyPiq4/sd2kz32EUinSMRUysa7Wx06Xm8dppvTFqyAt8oFk5f4ssai1CIKgqpzGhFSR21rtYckEnvfB1WVoT+qk6kHY0Lni280f4/vHGO1qRVP6bLo00jLR6zWqIJ9zViaGr8m3PCxhWzr7PBeZA8hH/VLucQ7REMw2F2m5IZEvedq8IZA6bCeh5h0oO0LpUSUhhy2xIkjtxpLbNURRR+9qRa1tI2QqgLCmk3Tj7vraVtz0nRHpdSGqSl4DzdTtw7iLOrtF9RgrvaJUBNb709hFBaePlmogqmItv6KerfZJmYww+ltKViUKhaJ3Fs+oT5h7/pXXuIwQF7RSkHGKs8LA+GFFYzy9wYfc8kepgVAVeIlF7te6SJYsDp9tWF18GzlsL3365gU5NaB94V7oOfoHYVibzoo+O92MPLo8zx3bC6kXR1HPj8b4zju0hE3uDVzf9+WVdnaSekvaqSQT1n0DnRglqVE= root@services.novalocal'
- hostname: compute06.hub.bca.gov.vn
  interfaces:
   - macAddress: fa:16:3e:14:b8:fd
     name: eth0
  networkConfig:
   interfaces:
     - name: eth0
       type: ethernet
       state: up
       mac-address: fa:16:3e:14:b8:fd
       ipv4:
         enabled: true
         address:
           - ip: 10.171.132.50
             prefix-length: 24
         dhcp: false
   dns-resolver:
     config:
       server:
       - 10.171.132.40
   routes:
     config:
     - destination: 0.0.0.0/0
       next-hop-address: 10.171.132.1
       next-hop-interface: eth0
       table-id: 254
  sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj3GM0JytAzH4k9IyQUQEAW8ZBpCNlGjKPLtyPiq4/sd2kz32EUinSMRUysa7Wx06Xm8dppvTFqyAt8oFk5f4ssai1CIKgqpzGhFSR21rtYckEnvfB1WVoT+qk6kHY0Lni280f4/vHGO1qRVP6bLo00jLR6zWqIJ9zViaGr8m3PCxhWzr7PBeZA8hH/VLucQ7REMw2F2m5IZEvedq8IZA6bCeh5h0oO0LpUSUhhy2xIkjtxpLbNURRR+9qRa1tI2QqgLCmk3Tj7vraVtz0nRHpdSGqSl4DzdTtw7iLOrtF9RgrvaJUBNb709hFBaePlmogqmItv6KerfZJmYww+ltKViUKhaJ3Fs+oT5h7/pXXuIwQF7RSkHGKs8LA+GFFYzy9wYfc8kepgVAVeIlF7te6SJYsDp9tWF18GzlsL3365gU5NaB94V7oOfoHYVibzoo+O92MPLo8zx3bC6kXR1HPj8b4zju0hE3uDVzf9+WVdnaSekvaqSQT1n0DnRglqVE= root@services.novalocal'
